### ISSUE TITLE
The backend API is no longer available

### ISSUE THREAD

**Issue by sampathsris** [isurunix/train-schedule#1]
It looks like railway.lankagate.gov.lk does not get resolved anymore. Do we have an alternate backend?

**Comment by isurunix** [comment]
Yeah, this not the official API endpoint. Need to rewrite the app to connect with the official API using proper auth keys.

**Comment by sampathsris** [comment]
And I assume the auth keys cannot be public? :) Do you know if the API publisher (is it ICTA) allows app developers to consume the API? If they did just that and implement throttles in the back-end to mitigate DoS attacks I guess the market/people will implement much better apps.

**Comment by isurunix** [comment]
Sorry for the long delay. I was kinda busy. Actually, they have an API but seems it's not public. I had to email them and fill a Google form to get the API access. 😃

**Comment by isurunix** [comment]
This issue is fixed in the latest release. 👍
