### ISSUE TITLE
How can I find Railway API ??

### ISSUE THREAD

**Issue by Kistlak** [isurunix/train-schedule#2]
I tried a lot of ways to find the API. But , I can't find it. Then how can I find the Sri Lanka Railway Schedule API ?? Please give me a reply.

Thank You,
Kistlak.

**Comment by wshsenanayaka** [comment]
Hi how to get this values ...

    "CONSUMER_KEY": "YOUR_CONSUMER_KEY",
    "CONSUMER_SECRET" : "YOUR_CONSUMER_SECRET",
    "TOKEN": null
form where .... 
thanks  ..

**Comment by roshiend** [comment]
> Hi how to get this values ...
> 
> ```
> "CONSUMER_KEY": "YOUR_CONSUMER_KEY",
> "CONSUMER_SECRET" : "YOUR_CONSUMER_SECRET",
> "TOKEN": null
> ```
> 
> form where ....
> thanks ..

right, u gotta contact ICTA for that. im here for the same reason tho.

**Comment by Sansith** [comment]
Is there anyone who got the access to the API?

**Comment by Kistlak** [comment]
If you want Railway API, you have to drop an email to **info@icta.lk**. They will contact you.

**Comment by Raveen-AJ** [comment]
> If you want Railway API, you have to drop an email to **[info@icta.lk](mailto:info@icta.lk)**. They will contact you.

They are not giving the API machan. they said contact railway and they said there is no process to give the API

**Comment by isurunix** [comment]
> > If you want Railway API, you have to drop an email to **[info@icta.lk](mailto:info@icta.lk)**. They will contact you.
> 
> They are not giving the API machan. they said contact railway and they said there is no process to give the API

Oh really. Those days they send me a Google Form to fill out and there was a process.

**Comment by madhurajayashanka** [comment]
@isurunix @Raveen-AJ @Kistlak @Sansith @roshiend @wshsenanayaka 
Hi guys is there any update on this? were you able to contact the administrations and get the API access or how did you work it out?

**Comment by isurunix** [comment]
It seems the API is no longer public. Even the domain https://api.lankagate.gov.lk/ is no longer resolved. So, if you are working on an application that requires access to train schedules, the best bet is to talk to ICTA or CGR.
